In [2]:
import pandas as pd
df = pd.read_csv("PremierLeagueMatches.csv")
df

,Matchday,Date,Time,Home Team,homeScore,homeXG,awayScore,awayXG,Away Team,Attendance,Referee,Stadium,Result,*Additional Stats
0,1,2022-08-05,20:00,Crystal Palace,0.0,1.2,2.0,1.0,Arsenal,"25,286",Anthony Taylor,Selhurst Park,A,https://fbref.com//en/matches/e62f6e78/Crystal...
1,1,2022-08-06,12:30,Fulham,2.0,1.2,2.0,1.2,Liverpool,"22,207",Andy Madley,Craven Cottage,D,https://fbref.com//en/matches/6713c1dc/Fulham-...
2,1,2022-08-06,15:00,Tottenham,4.0,1.5,1.0,0.5,Southampton,"61,732",Andre Marriner,Tottenham Hotspur Stadium,H,https://fbref.com//en/matches/09d8a999/Tottenh...
3,1,2022-08-06,15:00,Newcastle Utd,2.0,1.7,0.0,0.3,Nott'ham Forest,"52,245",Simon Hooper,St James' Park,H,https://fbref.com//en/matches/1ac96eb4/Newcast...
4,1,2022-08-06,15:00,Leeds United,2.0,0.8,1.0,1.3,Wolves,"36,347",Robert Jones,Elland Road,H,https://fbref.com//en/matches/82702941/Leeds-U...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1135,38,2025-05-25,16:00,Fulham,NaN,NaN,NaN,NaN,Manchester City,NaN,NaN,Craven Cottage,NaN,NaN
1136,38,2025-05-25,16:00,Nott'ham Forest,NaN,NaN,NaN,NaN,Chelsea,NaN,NaN,The City Ground,NaN,NaN
1137,38,2025-05-25,16:00,Manchester Utd,NaN,NaN,NaN,NaN,Aston Villa,NaN,NaN,Old Trafford,NaN,NaN
1138,38,2025-05-25,16:00,Wolves,NaN,NaN,NaN,NaN,Brentford,NaN,NaN,Molineux Stadium,NaN,NaN
1139,38,2025-05-25,16:00,Tottenham,NaN,NaN,NaN,NaN,Brighton,NaN,NaN,Tottenham Hotspur Stadium,NaN,NaN

In [3]:
#find the sha[e of dataframe
df.shape

(1140, 14)

In [4]:
df.info

<bound method DataFrame.info of       Matchday        Date   Time        Home Team  homeScore  homeXG  \
0            1  2022-08-05  20:00   Crystal Palace        0.0     1.2
1            1  2022-08-06  12:30           Fulham        2.0     1.2
2            1  2022-08-06  15:00        Tottenham        4.0     1.5
3            1  2022-08-06  15:00    Newcastle Utd        2.0     1.7
4            1  2022-08-06  15:00     Leeds United        2.0     0.8
...        ...         ...    ...              ...        ...     ...
1135        38  2025-05-25  16:00           Fulham        NaN     NaN
1136        38  2025-05-25  16:00  Nott'ham Forest        NaN     NaN
1137        38  2025-05-25  16:00   Manchester Utd        NaN     NaN
1138        38  2025-05-25  16:00           Wolves        NaN     NaN
1139        38  2025-05-25  16:00        Tottenham        NaN     NaN

      awayScore  awayXG        Away Team Attendance         Referee  \
0           2.0     1.0          Arsenal     25,286  Anthony Taylor
1           2.0     1.2        Liverpool     22,207     Andy Madley
2           1.0     0.5      Southampton     61,732  Andre Marriner
3           0.0     0.3  Nott'ham Forest     52,245    Simon Hooper
4           1.0     1.3           Wolves     36,347    Robert Jones
...         ...     ...              ...        ...             ...
1135        NaN     NaN  Manchester City        NaN             NaN
1136        NaN     NaN          Chelsea        NaN             NaN
1137        NaN     NaN      Aston Villa        NaN             NaN
1138        NaN     NaN        Brentford        NaN             NaN
1139        NaN     NaN         Brighton        NaN             NaN

                        Stadium Result  \
0                 Selhurst Park      A
1                Craven Cottage      D
2     Tottenham Hotspur Stadium      H
3                St James' Park      H
4                   Elland Road      H
...                         ...    ...
1135             Craven Cottage    NaN
1136            The City Ground    NaN
1137               Old Trafford    NaN
1138           Molineux Stadium    NaN
1139  Tottenham Hotspur Stadium    NaN

                                      *Additional Stats
0     https://fbref.com//en/matches/e62f6e78/Crystal...
1     https://fbref.com//en/matches/6713c1dc/Fulham-...
2     https://fbref.com//en/matches/09d8a999/Tottenh...
3     https://fbref.com//en/matches/1ac96eb4/Newcast...
4     https://fbref.com//en/matches/82702941/Leeds-U...
...                                                 ...
1135                                                NaN
1136                                                NaN
1137                                                NaN
1138                                                NaN
1139                                                NaN

[1140 rows x 14 columns]>

In [6]:
df.describe()

          Matchday    homeScore       homeXG    awayScore       awayXG
count  1140.000000  1049.000000  1049.000000  1049.000000  1049.000000
mean     19.500000     1.660629     1.626787     1.383222     1.316206
std      10.970669     1.364484     0.878962     1.237897     0.781492
min       1.000000     0.000000     0.000000     0.000000     0.000000
25%      10.000000     1.000000     1.000000     0.000000     0.800000
50%      19.500000     1.000000     1.500000     1.000000     1.200000
75%      29.000000     2.000000     2.200000     2.000000     1.700000
max      38.000000     9.000000     7.000000     8.000000     5.600000

In [12]:
df.isna().sum

<bound method DataFrame.sum of       Matchday   Date   Time  Home Team  homeScore  homeXG  awayScore  awayXG  \
0        False  False  False      False      False   False      False   False
1        False  False  False      False      False   False      False   False
2        False  False  False      False      False   False      False   False
3        False  False  False      False      False   False      False   False
4        False  False  False      False      False   False      False   False
...        ...    ...    ...        ...        ...     ...        ...     ...
1135     False  False  False      False       True    True       True    True
1136     False  False  False      False       True    True       True    True
1137     False  False  False      False       True    True       True    True
1138     False  False  False      False       True    True       True    True
1139     False  False  False      False       True    True       True    True

      Away Team  Attendance  Referee  Stadium  Result  *Additional Stats
0         False       False    False    False   False              False
1         False       False    False    False   False              False
2         False       False    False    False   False              False
3         False       False    False    False   False              False
4         False       False    False    False   False              False
...         ...         ...      ...      ...     ...                ...
1135      False        True     True    False    True               True
1136      False        True     True    False    True               True
1137      False        True     True    False    True               True
1138      False        True     True    False    True               True
1139      False        True     True    False    True               True

[1140 rows x 14 columns]>

In [13]:
df.count()

Matchday             1140
Date                 1140
Time                 1140
Home Team            1140
homeScore            1049
homeXG               1049
awayScore            1049
awayXG               1049
Away Team            1140
Attendance           1045
Referee              1049
Stadium              1140
Result               1049
*Additional Stats    1049
dtype: int64